# Book database for the book search program. Stores book and series details for genre filtering, sorting, and display.
#
# booklist is a dictionary with keys aligning to series or book titles. Values are dictionaries with attributes:
# - series_name (str): Name of series. Empty string for standalone books. "Series" without a defined order of events (can be read in any order) are treated as standalone books in a shared universe.
# - first_book (str): First book in the series (standalone books are a series of 1)
# - author (str): Name of the series author(s)
# - genres (list): List of genres for trie-based search
# - release_date (int): Publication year of the first book
# - rating (float): Goodreads rating (0-5)
# - length (int): Length in pages of first book. Kindle version for standardization when available.
# - series_length (int): Total length in pages of all books in the series. Kindle version when available.
# - num_books (int): Number of books in the series. 1 for standalone books.
# - shared_universe (str or False): If the book is part of a shared universe with other books or series, this will provide that. Also if a series of books are not in a defined order, they are classified as "shared universe" instead of series.
# - notes (str or False): Any additional details that might affect the reader's decision to start the series.

booklist = {
    "A Song of Ice and Fire": {
        "series_name": "A Song of Ice and Fire",
        "first_book": "A Game of Thrones",
        "author": "George R.R. Martin",
        "genres": ["fantasy", "epic fantasy", "high fantasy", "adventure"],
        "release_date": 1996,
        "rating": 4.45,
        "length": 835,
        "series_length": 4245,
        "num_books": 6,
        "shared_universe": "The World of Ice and Fire",
        "notes": "Ongoing series. Will likely never be finished by George R.R. Martin as writing the series that made him famous seems to be the last thing he wants to do."
    },
    "The Lord of the Rings": {
        "series_name": "The Lord of the Rings",
        "first_book": "The Fellowship of the Ring",
        "author": "J.R.R. Tolkein",
        "genres": ["fantasy", "epic fantasy", "high fantasy", "adventure", "classics"],
        "release_date": 1954,
        "rating": 4.4,
        "length": 432,
        "series_length": 1312,
        "num_books": 3,
        "shared_universe": "Middle-Earth",
        "notes": "Often credited with codifying the fantasy genre."
    },
    "A Study in Scarlet": {
        "series_name": "",
        "first_book": "A Study in Scarlet",
        "author": "Sir Arthur Conan Doyle",
        "genres": ["classics", "mystery", "historical fiction", "thriller"],
        "release_date": 1887,
        "rating": 4.13,
        "length": 123,
        "series_length": 123,
        "num_books": 1,
        "shared_universe": "The Complete Sherlock Holmes",
        "notes": False
    },
    "The Godfather": {
        "series_name": "",
        "first_book": "The Godfather",
        "author": "Mario Puzo",
        "genres": ["classics", "crime drama", "thriller", "historical fiction", "mystery", "drama"],
        "release_date": 1969,
        "rating": 4.4,
        "length": 448,
        "series_length": 448,
        "num_books": 1,
        "shared_universe": False,
        "notes": "The first of the Godfather film trilogy was based on this book, as were the flashbacks to Don Corleone's early life in the second film."
    },
    "The Saga of Tanya the Evil": {
        "series_name": "The Saga of Tanya the Evil",
        "first_book": "Deus lo Vult",
        "author": "Carlo Zen",
        "genres": ["light novel", "fantasy", "military fiction", "alternate history", "war"],
        "release_date": 2013,
        "rating": 4.15,
        "length": 344,
        "series_length": 4485,
        "num_books": 13,
        "shared_universe": False,
        "notes": "Ongoing series. Known as \"Youjo Senki\" in Japan, or \"The War Chronicles of a Little Girl\"."
    },
    "The Call of Cthulhu": {
        "series_name": "",
        "first_book": "The Call of Cthulhu",
        "author": "H. P. Lovecraft",
        "genres": ["horror", "classics", "short stories", "fantasy", "science fiction", "lovecraftian"],
        "release_date": 1928,
        "rating": 4.03,
        "length": 43,
        "series_length": 43,
        "num_books": 1,
        "shared_universe": "Cthulhu Mythos",
        "notes": "Credited with the creation of the concept of \"Lovecraftian horror\"."
    },
    "Darth Plagueis": {
        "series_name": "",
        "first_book": "Darth Plagueis",
        "author": "James Luceno",
        "genres": ["science fiction", "fantasy", "space opera"],
        "release_date": 2012,
        "rating": 4.19,
        "length": 461,
        "series_length": 461,
        "num_books": 1,
        "shared_universe": "Star Wars Legends",
        "notes": False
    },
    "Sword of Truth": {
        "series_name": "Sword of Truth",
        "first_book": "Wizard's First Rule",
        "author": "Terry Goodkind",
        "genres": ["fantasy", "epic fantasy", "high fantasy", "adventure", "magic"],
        "release_date": 1994,
        "rating": 4.12,
        "length": 836,
        "series_length": 8482,
        "num_books": 11,
        "shared_universe": "Sword of Truth Universe",
        "notes": "Highly contentious due to its Objectivist themes."
    },
    "Dune": {
        "series_name": "Dune",
        "first_book": "Dune",
        "author": "Frank Herbert",
        "genres": ["science fiction", "classics", "space opera", "speculative fiction"],
        "release_date": 1965,
        "rating": 4.25,
        "length": 794,
        "series_length": 3567,
        "num_books": 6,
        "shared_universe": "Dune Universe",
        "notes": False
    },
    "Catcher in the Rye": {
        "series_name": "",
        "first_book": "Catcher in the Rye",
        "author": "J.D. Salinger",
        "genres": ["classics", "young adult", "coming of age", "literary fiction"],
        "release_date": 1951,
        "rating": 3.81,
        "length": 277,
        "series_length": 277,
        "num_books": 1,
        "shared_universe": False,
        "notes": False
    },
    "My Side of the Mountain": {
        "series_name": "My Side of the Mountain",
        "first_book": "My Side of the Mountain",
        "author": "Jean Craighead George",
        "genres": ["young adult", "childrens", "classics", "adventure", "nature", "survival"],
        "release_date": 1959,
        "rating": 4.09,
        "length": 192,
        "series_length": 578,
        "num_books": 3,
        "shared_universe": False,
        "notes": False
    },
    "Atlas Shrugged": {
        "series_name": "",
        "first_book": "Atlas Shrugged",
        "author": "Ayn Rand",
        "genres": ["classics", "philosophy", "literature", "politics", "economics", "science fiction", "dystopia"],
        "release_date": 1957,
        "rating": 3.69,
        "length": 1168,
        "series_length": 1168,
        "num_books": 1,
        "shared_universe": False,
        "notes": "Highly contentious due to its Objectivist themes."
    },
    "Animal Farm": {
        "series_name": "",
        "first_book": "Animal Farm",
        "author": "George Orwell",
        "genres": ["classics", "dystopia", "politics", "literature", "satire"],
        "release_date": 1945,
        "rating": 3.99,
        "length": 112,
        "series_length": 112,
        "num_books": 1,
        "shared_universe": False,
        "notes": "Contentious due to its political themes as well as its perceived applicability to modern-day politics."
    },
    "War and Peace": {
        "series_name": "",
        "first_book": "War and Peace",
        "author": "Leo Tolstoy",
        "genres": ["classics", "historical fiction", "literature", "russian literature", "history", "war"],
        "release_date": 1865,
        "rating": 4.15,
        "length": 1225,
        "series_length": 1225,
        "num_books": 1,
        "shared_universe": False,
        "notes": False
    },
    "Moby Dick": {
        "series_name": "",
        "first_book": "Moby Dick",
        "author": "Herman Melville",
        "genres": ["classics", "literature", "adventure", "historical fiction"],
        "release_date": 1851,
        "rating": 3.54,
        "length": 654,
        "series_length": 654,
        "num_books": 1,
        "shared_universe": False,
        "notes": False
    },
    "David Copperfield": {
        "series_name": "",
        "first_book": "David Copperfield",
        "author": "Charles Dickens",
        "genres": ["classics", "literature", "historical fiction", "coming of age"],
        "release_date": 1850,
        "rating": 4.03,
        "length": 882,
        "series_length": 882,
        "num_books": 1,
        "shared_universe": False,
        "notes": False
    },
    "The Importance of Being Earnest": {
        "series_name": "",
        "first_book": "The Importance of Being Earnest",
        "author": "Oscar Wilde",
        "genres": ["classics", "plays", "drama", "literature", "comedy"],
        "release_date": 1895,
        "rating": 4.18,
        "length": 76,
        "series_length": 76,
        "num_books": 1,
        "shared_universe": False,
        "notes": False
    },
    "The Adventures of Tom Sawyer": {
        "series_name": "The Adventures of Tom and Huck",
        "first_book": "The Adventures of Tom Sawyer",
        "author": "Mark Twain",
        "genres": ["classics", "adventure", "literature", "young adult", "childrens"],
        "release_date": 1876,
        "rating": 3.92,
        "length": 244,
        "series_length": 614,
        "num_books": 4,
        "shared_universe": "Tom Sawyer",
        "notes": False
    },
    "Great Expectations": {
        "series_name": "",
        "first_book": "Great Expectations",
        "author": "Charles Dickens",
        "genres": ["classics", "literature", "historical fiction", "coming of age"],
        "release_date": 1861,
        "rating": 3.79,
        "length": 544,
        "series_length": 544,
        "num_books": 1,
        "shared_universe": False,
        "notes": False
    },
    "The Hunt for Red October": {
        "series_name": "",
        "first_book": "The Hunt for Red October",
        "author": "Tom Clancy",
        "genres": ["thriller", "military fiction", "suspense", "action", "espionage"],
        "release_date": 1984,
        "rating": 4.11,
        "length": 432,
        "series_length": 432,
        "num_books": 1,
        "shared_universe": "Adventures of Jack Ryan",
        "notes": "The third of the Jack Ryan novels."
    },
    "Casino Royale": {
        "series_name": "",
        "first_book": "Casino Royale",
        "author": "Ian Fleming",
        "genres": ["thriller", "espionage", "mystery", "action", "adventure"],
        "release_date": 1953,
        "rating": 3.74,
        "length": 213,
        "series_length": 213,
        "num_books": 1,
        "shared_universe": "The Adventures of James Bond",
        "notes": "First of the James Bond books"
    },
    "Dragonriders of Pern": {
        "series_name": "Dragonriders of Pern",
        "first_book": "Dragonflight",
        "author": "Anne McCaffrey",
        "genres": ["fantasy", "science fiction", "science fiction fantasy", "epic fantasy", "adventure"],
        "release_date": 1968,
        "rating": 4.11,
        "length": 320,
        "series_length": 6720,
        "num_books": 21,
        "shared_universe": "Pern",
        "notes": False
    },
    "The Handmaid's Tale": {
        "series_name": "The Handmaid's Tale",
        "first_book": "The Handmaid's Tale",
        "author": "Margaret Atwood",
        "genres": ["dystopia", "classics", "science fiction", "feminism", "literature", "speculative fiction"],
        "release_date": 1985,
        "rating": 4.14,
        "length": 311,
        "series_length": 625,
        "num_books": 2,
        "shared_universe": False,
        "notes": "Highly contentious due to its political themes as well as perceived applicability to modern politics."
    },
    "The Name of the Wind": {
        "series_name": "The Kingkiller Chronicle",
        "first_book": "The Name of the Wind",
        "author": "Patrick Rothfuss",
        "genres": ["fantasy", "epic fantasy", "high fantasy", "magic", "adventure"],
        "release_date": 2007,
        "rating": 4.52,
        "length": 662,
        "series_length": 1654,
        "num_books": 3,
        "shared_universe": "Kingkiller Chronicles Universe",
        "notes": "Ongoing series."
    },
    "Pride and Prejudice": {
        "series_name": "",
        "first_book": "Pride and Prejudice",
        "author": "Jane Austen",
        "genres": ["classics", "romance", "literature", "historical fiction"],
        "release_date": 1813,
        "rating": 4.28,
        "length": 432,
        "series_length": 432,
        "num_books": 1,
        "shared_universe": False,
        "notes": False
    },
    "The Wheel of Time": {
        "series_name": "The Wheel of Time",
        "first_book": "The Eye of the World",
        "author": "Robert Jordan, Brandon Sanderson",
        "genres": ["fantasy", "epic fantasy", "high fantasy", "adventure"],
        "release_date": 1990,
        "rating": 4.19,
        "length": 782,
        "series_length": 11898,
        "num_books": 14,
        "shared_universe": "Wheel of Time Universe",
        "notes": "Robert Jordan passed away before managing to finish the series himself. Brandon Sanderson finished the series based on Robert Jordan's notes. Some of the later books written by Robert Jordan are known as \"slog books\" due to them being considered tiresome."
    },
    "The Fairy Godmother": {
        "series_name": "",
        "first_book": "The Fairy Godmother",
        "author": "Mercedes Lackey",
        "genres": ["fantasy", "romance", "fairy tales", "romantic fantasy"],
        "release_date": 2004,
        "rating": 3.99,
        "length": 416,
        "series_length": 416,
        "num_books": 1,
        "shared_universe": "The Five Hundred Kingdoms",
        "notes": "First of the Five Hundred Kingdoms books."
    },
    "Harry Potter": {
        "series_name": "Harry Potter",
        "first_book": "Harry Potter and the Philosopher's Stone",
        "author": "J.K. Rowling",
        "genres": ["fantasy", "young adult", "childrens", "adventure"],
        "release_date": 1997,
        "rating": 4.47,
        "length": 324,
        "series_length": 4193,
        "num_books": 7,
        "shared_universe": "Wizarding World",
        "notes": False
    },
    "Typhon Pact": {
        "series_name": "Typhon Pact",
        "first_book": "Zero Sum Game",
        "author": "Various",
        "genres": ["science fiction", "space opera", "adventure"],
        "release_date": 2010,
        "rating": 3.78,
        "length": 337,
        "series_length": 2704,
        "num_books": 8,
        "shared_universe": "Star Trek",
        "notes": "Ongoing series. Zero Sum Game by David Mack. Other books in the series by various other authors."
    },
    "Dracula": {
        "series_name": "",
        "first_book": "Dracula",
        "author": "Bram Stoker",
        "genres": ["horror", "classics", "gothic horror", "fantasy", "literature"],
        "release_date": 1897,
        "rating": 4.02,
        "length": 418,
        "series_length": 418,
        "num_books": 1,
        "shared_universe": "Dracula Universe",
        "notes": False
    },
    "Animorphs": {
        "series_name": "Animorphs",
        "first_book": "The Invasion",
        "author": "K.A. Applegate",
        "genres": ["science fiction", "young adult", "childrens", "adventure"],
        "release_date": 1996,
        "rating": 3.89,
        "length": 192,
        "series_length": 10794,
        "num_books": 62,
        "shared_universe": "Animorphs Universe",
        "notes": False
    },
    "The Outsiders": {
        "series_name": "",
        "first_book": "The Outsiders",
        "author": "S.E. Hinton",
        "genres": ["young adult", "classics", "coming of age", "literature"],
        "release_date": 1967,
        "rating": 4.13,
        "length": 194,
        "series_length": 194,
        "num_books": 1,
        "shared_universe": False,
        "notes": False
    },
    "A Tale of Two Cities": {
        "series_name": "",
        "first_book": "A Tale of Two Cities",
        "author": "Charles Dickens",
        "genres": ["classics", "fiction", "historical fiction", "literature"],
        "release_date": 1859,
        "rating": 3.87,
        "length": 489,
        "series_length": 489,
        "num_books": 1,
        "shared_universe": False,
        "notes": False
    },
    "Crime and Punishment": {
        "series_name": "",
        "first_book": "Crime and Punishment",
        "author": "Fyodor Dostoevsky",
        "genres": ["classics", "literature", "russian literature", "philosophy"],
        "release_date": 1866,
        "rating": 4.27,
        "length": 671,
        "series_length": 671,
        "num_books": 1,
        "shared_universe": False,
        "notes": False
    },
    "Haruhi Suzumiya": {
        "series_name": "Haruhi Suzumiya",
        "first_book": "The Melancholy of Haruhi Suzumiya",
        "author": "Nagaru Tanigawa",
        "genres": ["light novel", "science fiction", "fantasy", "young adult", "comedy", "mystery"],
        "release_date": 2003,
        "rating": 4.02,
        "length": 208,
        "series_length": 2608,
        "num_books": 12,
        "shared_universe": "Haruhi Suzumiya Universe",
        "notes": "Ongoing series. Originally considered to have finished in 2011, new books have been published starting in 2020. The stories are often presented out of order, but do reference each other as a sequence. The Haruhi Wiki provides a timeline of stories in chronological order in-universe."
    },
    "Dragonlance Chronicles": {
        "series_name": "Dragonlance Chronicles",
        "first_book": "Dragons of Autumn Twilight",
        "author": "Margaret Weis, Tracy Hickman",
        "genres": ["fantasy", "epic fantasy", "high fantasy", "adventure"],
        "release_date": 1984,
        "rating": 4.03,
        "length": 447,
        "series_length": 1377,
        "num_books": 3,
        "shared_universe": "Dragonlance Universe",
        "notes": False
    },
    "The Shadow Series": {
        "series_name": "The Shadow Series",
        "first_book": "Ender's Shadow",
        "author": "Orson Scott Card",
        "genres": ["science fiction", "military science fiction", "young adult", "war", "dystopia", "speculative fiction", "adventure"],
        "release_date": 1999,
        "rating": 4.32,
        "length": 484,
        "series_length": 1923,
        "num_books": 5,
        "shared_universe": "Ender's Game",
        "notes": "The first book in the series, Ender's Shadow, follows the events of Ender's Game from Bean's perspective."
    }
}